import type { Metadata } from "next";
import { Ubuntu, Ubuntu_Mono } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({
    variable: "--font-sans",
    weight: '400',
    subsets: ["latin"],
});

const ubuntuMono = Ubuntu_Mono({
    variable: "--font-mono",
    weight: '400',
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${ubuntu.variable} ${ubuntuMono.variable} h-full antialiased`}
        >
            <body className="min-h-full max-w-7xl block mx-auto bg-gray-100">
                {children}
            </body>
        </html>
    );
}
